development:
  adapter: postgresql
  encoding: unicode
  database: miniFunzing
  pool: 5
  username: postgres
  password: rotemcohen
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: miniFunzing
  pool: 5
  username: postgres
  password: rotemcohen
  host: localhost
  port: 5432
